#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v23
# autospec commit: 247c192
#
Name     : glfw
Version  : 3.4
Release  : 11
URL      : https://github.com/glfw/glfw/archive/3.4/glfw-3.4.tar.gz
Source0  : https://github.com/glfw/glfw/archive/3.4/glfw-3.4.tar.gz
Summary  : A multi-platform library for OpenGL, window and input
Group    : Development/Tools
License  : Zlib
Requires: glfw-lib = %{version}-%{release}
Requires: glfw-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : doxygen
BuildRequires : glibc-dev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXau-dev
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXdamage-dev
BuildRequires : libXdmcp-dev
BuildRequires : libXext-dev
BuildRequires : libXfixes-dev
BuildRequires : libXft-dev
BuildRequires : libXi-dev
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXpm-dev
BuildRequires : libXrandr-dev
BuildRequires : libXrender-dev
BuildRequires : libXres-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libXv-dev
BuildRequires : libXxf86vm-dev
BuildRequires : mesa-dev
BuildRequires : wayland
BuildRequires : wayland-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# GLFW
[![Build status](https://github.com/glfw/glfw/actions/workflows/build.yml/badge.svg)](https://github.com/glfw/glfw/actions)
[![Build status](https://ci.appveyor.com/api/projects/status/0kf0ct9831i5l6sp/branch/master?svg=true)](https://ci.appveyor.com/project/elmindreda/glfw)

%package dev
Summary: dev components for the glfw package.
Group: Development
Requires: glfw-lib = %{version}-%{release}
Provides: glfw-devel = %{version}-%{release}
Requires: glfw = %{version}-%{release}

%description dev
dev components for the glfw package.


%package doc
Summary: doc components for the glfw package.
Group: Documentation

%description doc
doc components for the glfw package.


%package lib
Summary: lib components for the glfw package.
Group: Libraries
Requires: glfw-license = %{version}-%{release}

%description lib
lib components for the glfw package.


%package license
Summary: license components for the glfw package.
Group: Default

%description license
license components for the glfw package.


%prep
%setup -q -n glfw-3.4
cd %{_builddir}/glfw-3.4
pushd ..
cp -a glfw-3.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1743784488
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DLIB_SUFFIX=64  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DLIB_SUFFIX=64  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1743784488
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/glfw
cp %{_builddir}/glfw-%{version}/LICENSE.md %{buildroot}/usr/share/package-licenses/glfw/55822a091dca212023dfde6e6fb53df49288dbd8 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/GLFW/glfw3.h
/usr/include/GLFW/glfw3native.h
/usr/lib64/cmake/glfw3/glfw3Config.cmake
/usr/lib64/cmake/glfw3/glfw3ConfigVersion.cmake
/usr/lib64/cmake/glfw3/glfw3Targets-relwithdebinfo.cmake
/usr/lib64/cmake/glfw3/glfw3Targets.cmake
/usr/lib64/libglfw.so
/usr/lib64/pkgconfig/glfw3.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/GLFW/html/bc_s.png
/usr/share/doc/GLFW/html/bc_sd.png
/usr/share/doc/GLFW/html/build_8md.html
/usr/share/doc/GLFW/html/build_guide.html
/usr/share/doc/GLFW/html/closed.png
/usr/share/doc/GLFW/html/compat_8md.html
/usr/share/doc/GLFW/html/compat_guide.html
/usr/share/doc/GLFW/html/compile_8md.html
/usr/share/doc/GLFW/html/compile_guide.html
/usr/share/doc/GLFW/html/context_8md.html
/usr/share/doc/GLFW/html/context_guide.html
/usr/share/doc/GLFW/html/deprecated.html
/usr/share/doc/GLFW/html/dir_49e56c817e5e54854c35e136979f97ca.html
/usr/share/doc/GLFW/html/dir_7d046523570a4bf058ddf3b10b545b6c.html
/usr/share/doc/GLFW/html/dir_d44c64559bbebec7f509842c48db8b23.html
/usr/share/doc/GLFW/html/doc.svg
/usr/share/doc/GLFW/html/docd.svg
/usr/share/doc/GLFW/html/doxygen.css
/usr/share/doc/GLFW/html/doxygen.svg
/usr/share/doc/GLFW/html/dynsections.js
/usr/share/doc/GLFW/html/extra.css
/usr/share/doc/GLFW/html/files.html
/usr/share/doc/GLFW/html/folderclosed.svg
/usr/share/doc/GLFW/html/folderclosedd.svg
/usr/share/doc/GLFW/html/folderopen.svg
/usr/share/doc/GLFW/html/folderopend.svg
/usr/share/doc/GLFW/html/glfw3_8h.html
/usr/share/doc/GLFW/html/glfw3_8h_source.html
/usr/share/doc/GLFW/html/glfw3native_8h.html
/usr/share/doc/GLFW/html/glfw3native_8h_source.html
/usr/share/doc/GLFW/html/group__buttons.html
/usr/share/doc/GLFW/html/group__context.html
/usr/share/doc/GLFW/html/group__errors.html
/usr/share/doc/GLFW/html/group__gamepad__axes.html
/usr/share/doc/GLFW/html/group__gamepad__buttons.html
/usr/share/doc/GLFW/html/group__hat__state.html
/usr/share/doc/GLFW/html/group__init.html
/usr/share/doc/GLFW/html/group__input.html
/usr/share/doc/GLFW/html/group__joysticks.html
/usr/share/doc/GLFW/html/group__keys.html
/usr/share/doc/GLFW/html/group__mods.html
/usr/share/doc/GLFW/html/group__monitor.html
/usr/share/doc/GLFW/html/group__native.html
/usr/share/doc/GLFW/html/group__shapes.html
/usr/share/doc/GLFW/html/group__vulkan.html
/usr/share/doc/GLFW/html/group__window.html
/usr/share/doc/GLFW/html/index.html
/usr/share/doc/GLFW/html/input_8md.html
/usr/share/doc/GLFW/html/input_guide.html
/usr/share/doc/GLFW/html/internal_8md.html
/usr/share/doc/GLFW/html/internals_guide.html
/usr/share/doc/GLFW/html/intro_8md.html
/usr/share/doc/GLFW/html/intro_guide.html
/usr/share/doc/GLFW/html/jquery.js
/usr/share/doc/GLFW/html/main_8md.html
/usr/share/doc/GLFW/html/menu.js
/usr/share/doc/GLFW/html/menudata.js
/usr/share/doc/GLFW/html/minus.svg
/usr/share/doc/GLFW/html/minusd.svg
/usr/share/doc/GLFW/html/monitor_8md.html
/usr/share/doc/GLFW/html/monitor_guide.html
/usr/share/doc/GLFW/html/moving_8md.html
/usr/share/doc/GLFW/html/moving_guide.html
/usr/share/doc/GLFW/html/nav_f.png
/usr/share/doc/GLFW/html/nav_fd.png
/usr/share/doc/GLFW/html/nav_g.png
/usr/share/doc/GLFW/html/nav_h.png
/usr/share/doc/GLFW/html/nav_hd.png
/usr/share/doc/GLFW/html/news.html
/usr/share/doc/GLFW/html/news_8md.html
/usr/share/doc/GLFW/html/open.png
/usr/share/doc/GLFW/html/pages.html
/usr/share/doc/GLFW/html/plus.svg
/usr/share/doc/GLFW/html/plusd.svg
/usr/share/doc/GLFW/html/quick_8md.html
/usr/share/doc/GLFW/html/quick_guide.html
/usr/share/doc/GLFW/html/search/all_0.js
/usr/share/doc/GLFW/html/search/all_1.js
/usr/share/doc/GLFW/html/search/all_10.js
/usr/share/doc/GLFW/html/search/all_11.js
/usr/share/doc/GLFW/html/search/all_12.js
/usr/share/doc/GLFW/html/search/all_13.js
/usr/share/doc/GLFW/html/search/all_14.js
/usr/share/doc/GLFW/html/search/all_15.js
/usr/share/doc/GLFW/html/search/all_16.js
/usr/share/doc/GLFW/html/search/all_17.js
/usr/share/doc/GLFW/html/search/all_18.js
/usr/share/doc/GLFW/html/search/all_19.js
/usr/share/doc/GLFW/html/search/all_1a.js
/usr/share/doc/GLFW/html/search/all_1b.js
/usr/share/doc/GLFW/html/search/all_1c.js
/usr/share/doc/GLFW/html/search/all_1d.js
/usr/share/doc/GLFW/html/search/all_1e.js
/usr/share/doc/GLFW/html/search/all_1f.js
/usr/share/doc/GLFW/html/search/all_2.js
/usr/share/doc/GLFW/html/search/all_3.js
/usr/share/doc/GLFW/html/search/all_4.js
/usr/share/doc/GLFW/html/search/all_5.js
/usr/share/doc/GLFW/html/search/all_6.js
/usr/share/doc/GLFW/html/search/all_7.js
/usr/share/doc/GLFW/html/search/all_8.js
/usr/share/doc/GLFW/html/search/all_9.js
/usr/share/doc/GLFW/html/search/all_a.js
/usr/share/doc/GLFW/html/search/all_b.js
/usr/share/doc/GLFW/html/search/all_c.js
/usr/share/doc/GLFW/html/search/all_d.js
/usr/share/doc/GLFW/html/search/all_e.js
/usr/share/doc/GLFW/html/search/all_f.js
/usr/share/doc/GLFW/html/search/classes_0.js
/usr/share/doc/GLFW/html/search/close.svg
/usr/share/doc/GLFW/html/search/defines_0.js
/usr/share/doc/GLFW/html/search/files_0.js
/usr/share/doc/GLFW/html/search/files_1.js
/usr/share/doc/GLFW/html/search/files_2.js
/usr/share/doc/GLFW/html/search/files_3.js
/usr/share/doc/GLFW/html/search/files_4.js
/usr/share/doc/GLFW/html/search/files_5.js
/usr/share/doc/GLFW/html/search/files_6.js
/usr/share/doc/GLFW/html/search/files_7.js
/usr/share/doc/GLFW/html/search/files_8.js
/usr/share/doc/GLFW/html/search/functions_0.js
/usr/share/doc/GLFW/html/search/groups_0.js
/usr/share/doc/GLFW/html/search/groups_1.js
/usr/share/doc/GLFW/html/search/groups_10.js
/usr/share/doc/GLFW/html/search/groups_2.js
/usr/share/doc/GLFW/html/search/groups_3.js
/usr/share/doc/GLFW/html/search/groups_4.js
/usr/share/doc/GLFW/html/search/groups_5.js
/usr/share/doc/GLFW/html/search/groups_6.js
/usr/share/doc/GLFW/html/search/groups_7.js
/usr/share/doc/GLFW/html/search/groups_8.js
/usr/share/doc/GLFW/html/search/groups_9.js
/usr/share/doc/GLFW/html/search/groups_a.js
/usr/share/doc/GLFW/html/search/groups_b.js
/usr/share/doc/GLFW/html/search/groups_c.js
/usr/share/doc/GLFW/html/search/groups_d.js
/usr/share/doc/GLFW/html/search/groups_e.js
/usr/share/doc/GLFW/html/search/groups_f.js
/usr/share/doc/GLFW/html/search/mag.svg
/usr/share/doc/GLFW/html/search/mag_d.svg
/usr/share/doc/GLFW/html/search/mag_sel.svg
/usr/share/doc/GLFW/html/search/mag_seld.svg
/usr/share/doc/GLFW/html/search/pages_0.js
/usr/share/doc/GLFW/html/search/pages_1.js
/usr/share/doc/GLFW/html/search/pages_10.js
/usr/share/doc/GLFW/html/search/pages_11.js
/usr/share/doc/GLFW/html/search/pages_2.js
/usr/share/doc/GLFW/html/search/pages_3.js
/usr/share/doc/GLFW/html/search/pages_4.js
/usr/share/doc/GLFW/html/search/pages_5.js
/usr/share/doc/GLFW/html/search/pages_6.js
/usr/share/doc/GLFW/html/search/pages_7.js
/usr/share/doc/GLFW/html/search/pages_8.js
/usr/share/doc/GLFW/html/search/pages_9.js
/usr/share/doc/GLFW/html/search/pages_a.js
/usr/share/doc/GLFW/html/search/pages_b.js
/usr/share/doc/GLFW/html/search/pages_c.js
/usr/share/doc/GLFW/html/search/pages_d.js
/usr/share/doc/GLFW/html/search/pages_e.js
/usr/share/doc/GLFW/html/search/pages_f.js
/usr/share/doc/GLFW/html/search/search.css
/usr/share/doc/GLFW/html/search/search.js
/usr/share/doc/GLFW/html/search/searchdata.js
/usr/share/doc/GLFW/html/search/typedefs_0.js
/usr/share/doc/GLFW/html/search/variables_0.js
/usr/share/doc/GLFW/html/search/variables_1.js
/usr/share/doc/GLFW/html/search/variables_2.js
/usr/share/doc/GLFW/html/search/variables_3.js
/usr/share/doc/GLFW/html/search/variables_4.js
/usr/share/doc/GLFW/html/search/variables_5.js
/usr/share/doc/GLFW/html/search/variables_6.js
/usr/share/doc/GLFW/html/search/variables_7.js
/usr/share/doc/GLFW/html/search/variables_8.js
/usr/share/doc/GLFW/html/search/variables_9.js
/usr/share/doc/GLFW/html/spaces.svg
/usr/share/doc/GLFW/html/splitbar.png
/usr/share/doc/GLFW/html/splitbard.png
/usr/share/doc/GLFW/html/structGLFWallocator.html
/usr/share/doc/GLFW/html/structGLFWgamepadstate.html
/usr/share/doc/GLFW/html/structGLFWgammaramp.html
/usr/share/doc/GLFW/html/structGLFWimage.html
/usr/share/doc/GLFW/html/structGLFWvidmode.html
/usr/share/doc/GLFW/html/sync_off.png
/usr/share/doc/GLFW/html/sync_on.png
/usr/share/doc/GLFW/html/tab_a.png
/usr/share/doc/GLFW/html/tab_ad.png
/usr/share/doc/GLFW/html/tab_b.png
/usr/share/doc/GLFW/html/tab_bd.png
/usr/share/doc/GLFW/html/tab_h.png
/usr/share/doc/GLFW/html/tab_hd.png
/usr/share/doc/GLFW/html/tab_s.png
/usr/share/doc/GLFW/html/tab_sd.png
/usr/share/doc/GLFW/html/tabs.css
/usr/share/doc/GLFW/html/topics.html
/usr/share/doc/GLFW/html/vulkan_8md.html
/usr/share/doc/GLFW/html/vulkan_guide.html
/usr/share/doc/GLFW/html/window_8md.html
/usr/share/doc/GLFW/html/window_guide.html

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libglfw.so.3.4
/usr/lib64/libglfw.so.3
/usr/lib64/libglfw.so.3.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/glfw/55822a091dca212023dfde6e6fb53df49288dbd8
